/*
 * Copyright 2025 Sami Malik
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * Author: Sami Malik (sami.malik [at] portolanetwork.io)
 */

package app.dragon.turnstile.db

import app.dragon.turnstile.db.TurnstilePostgresProfile.api.{*, given}

import java.sql.Timestamp
import java.util.UUID

/**
 * Slick table definitions for MCP server persistence.
 *
 * Database Schema:
 * - mcp_server: Stores user-registered MCP servers
 *   - id: Auto-incrementing primary key
 *   - uuid: Server UUID (globally unique across entire table)
 *   - tenant: Tenant identifier for multi-tenancy
 *   - user_id: User identifier
 *   - name: Server name (unique per tenant+user combination)
 *   - url: Server URL
 *   - client_id: OAuth client ID (optional)
 *   - client_secret: OAuth client secret (optional)
 *   - refresh_token: OAuth refresh token (optional)
 *   - token_endpoint: OAuth token endpoint URL (optional)
 *   - auth_type: Authentication type (none, discover, or static_auth_header)
 *   - static_token: Static authentication token (optional)
 *   - created_at: Timestamp of creation
 *   - updated_at: Timestamp of last update
 *
 * Indexes:
 * - idx_mcp_servers_tenant: Fast lookup by tenant
 * - idx_mcp_servers_tenant_user: Lookup by tenant and user
 * - idx_mcp_servers_uuid: Unique constraint on uuid
 * - idx_mcp_servers_tenant_user_name: Unique constraint on (tenant, user_id, name)
 */

/**
 * MCP server table row representation
 *
 * @param id Auto-incrementing primary key
 * @param uuid Server UUID (globally unique across entire table)
 * @param tenant Tenant identifier
 * @param userId User identifier
 * @param name Server name (unique per tenant+user combination)
 * @param url Server URL
 * @param clientId OAuth client ID (optional)
 * @param clientSecret OAuth client secret (optional)
 * @param refreshToken OAuth refresh token (optional)
 * @param tokenEndpoint OAuth token endpoint URL (optional)
 * @param authType Authentication type: none, discover, or static_auth_header
 * @param staticToken Static authentication token (optional)
 * @param createdAt Creation timestamp
 * @param updatedAt Last update timestamp
 */
case class McpServerRow(
  id: Long = 0L,
  uuid: UUID = UUID.randomUUID(), // Placeholder value; actual UUID generated by database
  tenant: String,
  userId: String,
  name: String,
  url: String,
  clientId: Option[String] = None,
  clientSecret: Option[String] = None,
  refreshToken: Option[String] = None,
  tokenEndpoint: Option[String] = None,
  authType: String = "none",
  staticToken: Option[String] = None,
  createdAt: Timestamp = new Timestamp(System.currentTimeMillis()),
  updatedAt: Timestamp = new Timestamp(System.currentTimeMillis())
)

/**
 * Slick table definition for mcp_server
 */
class McpServersTable(
  tag: Tag
) extends Table[McpServerRow](tag, "mcp_server") {
  def id = column[Long]("id", O.PrimaryKey, O.AutoInc)
  def uuid = column[UUID]("uuid", O.Default(java.util.UUID.randomUUID()))
  def tenant = column[String]("tenant")
  def userId = column[String]("user_id")
  def name = column[String]("name")
  def url = column[String]("url")
  def clientId = column[Option[String]]("client_id")
  def clientSecret = column[Option[String]]("client_secret")
  def refreshToken = column[Option[String]]("refresh_token")
  def tokenEndpoint = column[Option[String]]("token_endpoint")
  def authType = column[String]("auth_type", O.Default("none"))
  def staticToken = column[Option[String]]("static_token")
  def createdAt = column[Timestamp]("created_at")
  def updatedAt = column[Timestamp]("updated_at")

  // Index on tenant for fast lookup
  def idxTenant = index("idx_mcp_servers_tenant", tenant)

  // Index on (tenant, user_id)
  def idxTenantUser = index("idx_mcp_servers_tenant_user", (tenant, userId))

  // Unique index on uuid (globally unique)
  def idxUuid = index("idx_mcp_servers_uuid", uuid, unique = true)

  // Unique index on (tenant, user_id, name)
  def idxTenantUserName = index("idx_mcp_servers_tenant_user_name", (tenant, userId, name), unique = true)

  def * = (id, uuid, tenant, userId, name, url, clientId, clientSecret, refreshToken, tokenEndpoint, authType, staticToken, createdAt, updatedAt).mapTo[McpServerRow]
}

/**
 * Table queries object for accessing tables
 */
object Tables {
  /**
   * MCP servers table query
   */
  val mcpServers = TableQuery[McpServersTable]
}
