/*
 * Copyright 2025 Sami Malik
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * Author: Sami Malik (sami.malik [at] portolanetwork.io)
 */

package app.dragon.turnstile.db

import app.dragon.turnstile.db.TurnstilePostgresProfile.api.*
import play.api.libs.json.JsValue

import java.sql.Timestamp
import java.util.UUID

/**
 * Slick table definitions for MCP server persistence.
 *
 * Database Schema:
 * - mcp_server: Stores user-registered MCP servers
 *   - id: Auto-incrementing primary key
 *   - uuid: Server UUID (globally unique across entire table)
 *   - tenant: Tenant identifier for multi-tenancy
 *   - user_id: User identifier
 *   - name: Server name (unique per tenant+user combination)
 *   - url: Server URL
 *   - client_id: OAuth client ID (optional)
 *   - client_secret: OAuth client secret (optional)
 *   - refresh_token: OAuth refresh token (optional)
 *   - token_endpoint: OAuth token endpoint URL (optional)
 *   - auth_type: Authentication type (none, discover, or static_auth_header)
 *   - static_token: Static authentication token (optional)
 *   - transport_type: Transport type (streaming_http)
 *   - created_at: Timestamp of creation
 *   - updated_at: Timestamp of last update
 *
 * Indexes:
 * - idx_mcp_servers_tenant: Fast lookup by tenant
 * - idx_mcp_servers_tenant_user: Lookup by tenant and user
 * - idx_mcp_servers_uuid: Unique constraint on uuid
 * - idx_mcp_servers_tenant_user_name: Unique constraint on (tenant, user_id, name)
 */

/**
 * MCP server table row representation
 *
 * @param id Auto-incrementing primary key
 * @param uuid Server UUID (globally unique across entire table)
 * @param tenant Tenant identifier
 * @param userId User identifier
 * @param name Server name (unique per tenant+user combination)
 * @param url Server URL
 * @param clientId OAuth client ID (optional)
 * @param clientSecret OAuth client secret (optional)
 * @param refreshToken OAuth refresh token (optional)
 * @param tokenEndpoint OAuth token endpoint URL (optional)
 * @param authType Authentication type: none, discover, or static_auth_header
 * @param staticToken Static authentication token (optional)
 * @param transportType Transport type: streaming_http
 * @param createdAt Creation timestamp
 * @param updatedAt Last update timestamp
 */
case class McpServerRow(
  id: Long = 0L,
  uuid: UUID = UUID.randomUUID(), // Placeholder value; actual UUID generated by database
  tenant: String,
  userId: String,
  name: String,
  url: String,
  clientId: Option[String] = None,
  clientSecret: Option[String] = None,
  refreshToken: Option[String] = None,
  tokenEndpoint: Option[String] = None,
  authType: String = "none",
  staticToken: Option[String] = None,
  transportType: String = "streaming_http",
  createdAt: Timestamp = new Timestamp(System.currentTimeMillis()),
  updatedAt: Timestamp = new Timestamp(System.currentTimeMillis())
)

/**
 * Slick table definition for mcp_server
 */
class McpServersTable(
  tag: Tag
) extends Table[McpServerRow](tag, "mcp_server") {
  def id = column[Long]("id", O.PrimaryKey, O.AutoInc)
  def uuid = column[UUID]("uuid", O.Default(java.util.UUID.randomUUID()))
  def tenant = column[String]("tenant")
  def userId = column[String]("user_id")
  def name = column[String]("name")
  def url = column[String]("url")
  def clientId = column[Option[String]]("client_id")
  def clientSecret = column[Option[String]]("client_secret")
  def refreshToken = column[Option[String]]("refresh_token")
  def tokenEndpoint = column[Option[String]]("token_endpoint")
  def authType = column[String]("auth_type", O.Default("none"))
  def staticToken = column[Option[String]]("static_token")
  def transportType = column[String]("transport_type", O.Default("streaming_http"))
  def createdAt = column[Timestamp]("created_at")
  def updatedAt = column[Timestamp]("updated_at")

  // Index on tenant for fast lookup
  def idxTenant = index("idx_mcp_servers_tenant", tenant)

  // Index on (tenant, user_id)
  def idxTenantUser = index("idx_mcp_servers_tenant_user", (tenant, userId))

  // Unique index on uuid (globally unique)
  def idxUuid = index("idx_mcp_servers_uuid", uuid, unique = true)

  // Unique index on (tenant, user_id, name)
  def idxTenantUserName = index("idx_mcp_servers_tenant_user_name", (tenant, userId, name), unique = true)

  def * = (id, uuid, tenant, userId, name, url, clientId, clientSecret, refreshToken, tokenEndpoint, authType, staticToken, transportType, createdAt, updatedAt).mapTo[McpServerRow]
}

/**
 * Event log table row representation
 *
 * @param id Auto-incrementing primary key
 * @param uuid Event UUID (globally unique)
 * @param tenant Tenant identifier
 * @param userId User identifier (nullable for system events)
 * @param eventType Event type (e.g., fetch_tools, get, post, login, client_connected)
 * @param description Human-readable event description
 * @param sourceType Source type (e.g., mcp_server, system, client) for event origin classification
 * @param sourceUuid UUID reference to the source entity (no FK constraint)
 * @param rawData Extensible JSONB field for event-specific data (JsNull for empty)
 * @param createdAt Creation timestamp
 */
case class EventLogRow(
  id: Long = 0L,
  uuid: UUID = UUID.randomUUID(), // Placeholder value; actual UUID generated by database
  tenant: String,
  userId: Option[String] = None,
  eventType: String,
  description: Option[String] = None,
  sourceType: Option[String] = None,
  sourceUuid: Option[UUID] = None,
  rawData: JsValue = play.api.libs.json.JsNull,
  createdAt: Timestamp = new Timestamp(System.currentTimeMillis())
)

/**
 * Slick table definition for event_log
 *
 * Uses custom JSONB support from TurnstilePostgresProfile with PGobject for proper JSONB handling.
 */
class EventLogTable(
  tag: Tag
) extends Table[EventLogRow](tag, "event_log") {
  // Explicitly import JSONB type mapper
  import app.dragon.turnstile.db.TurnstilePostgresProfile.TurnstileAPI.playJsonTypeMapper

  def id = column[Long]("id", O.PrimaryKey, O.AutoInc)
  def uuid = column[UUID]("uuid", O.Default(java.util.UUID.randomUUID()))
  def tenant = column[String]("tenant")
  def userId = column[Option[String]]("user_id")
  def eventType = column[String]("event_type")
  def description = column[Option[String]]("description")
  def sourceType = column[Option[String]]("source_type")
  def sourceUuid = column[Option[UUID]]("source_uuid")
  def rawData = column[JsValue]("raw_data")
  def createdAt = column[Timestamp]("created_at")

  // Index on tenant for fast lookup
  def idxTenant = index("idx_event_log_tenant", tenant)

  // Index on (tenant, user_id)
  def idxTenantUser = index("idx_event_log_tenant_user", (tenant, userId))

  // Index on event_type
  def idxEventType = index("idx_event_log_event_type", eventType)

  // Index on source_type
  def idxSourceType = index("idx_event_log_source_type", sourceType)

  // Index on source_uuid
  def idxSourceUuid = index("idx_event_log_source_uuid", sourceUuid)

  // Index on created_at
  def idxCreatedAt = index("idx_event_log_created_at", createdAt)

  // Unique index on uuid (globally unique)
  def idxUuid = index("idx_event_log_uuid", uuid, unique = true)

  def * = (id, uuid, tenant, userId, eventType, description, sourceType, sourceUuid, rawData, createdAt).mapTo[EventLogRow]
}

/**
 * Table queries object for accessing tables
 */
object Tables {
  /**
   * MCP servers table query
   */
  val mcpServers = TableQuery[McpServersTable]

  /**
   * Event log table query
   */
  val eventLogs = TableQuery[EventLogTable]
}
