// @generated by protobuf-ts 2.9.4
// @generated from protobuf file "portola/spyder/v1/common.proto" (package "portola.spyder.api.v1", syntax proto3)
// tslint:disable
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
/**
 * @generated from protobuf message portola.spyder.api.v1.GrpcResponse
 */
export interface GrpcResponse {
    /**
     * @generated from protobuf field: portola.spyder.api.v1.ServingStatus status = 1;
     */
    status: ServingStatus;
}
/**
 * @generated from protobuf enum portola.spyder.api.v1.ServingStatus
 */
export enum ServingStatus {
    /**
     * @generated from protobuf enum value: UNSPECIFIED = 0;
     */
    UNSPECIFIED = 0,
    /**
     * @generated from protobuf enum value: OK = 1;
     */
    OK = 1,
    /**
     * @generated from protobuf enum value: ACCEPTED = 2;
     */
    ACCEPTED = 2
}
// @generated message type with reflection information, may provide speed optimized methods
class GrpcResponse$Type extends MessageType<GrpcResponse> {
    constructor() {
        super("portola.spyder.api.v1.GrpcResponse", [
            { no: 1, name: "status", kind: "enum", T: () => ["portola.spyder.api.v1.ServingStatus", ServingStatus] }
        ]);
    }
    create(value?: PartialMessage<GrpcResponse>): GrpcResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.status = 0;
        if (value !== undefined)
            reflectionMergePartial<GrpcResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GrpcResponse): GrpcResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* portola.spyder.api.v1.ServingStatus status */ 1:
                    message.status = reader.int32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GrpcResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* portola.spyder.api.v1.ServingStatus status = 1; */
        if (message.status !== 0)
            writer.tag(1, WireType.Varint).int32(message.status);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message portola.spyder.api.v1.GrpcResponse
 */
export const GrpcResponse = new GrpcResponse$Type();
