// @generated by protobuf-ts 2.9.4
// @generated from protobuf file "portola/spyder/v1/spyder_service.proto" (package "portola.spyder.api.v1", syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { SpyderService } from "./spyder_service";
import type { Token } from "./spyder_service";
import type { CreateStripePortalSessionResponse } from "./spyder_service";
import type { CreateStripePortalSessionRequest } from "./spyder_service";
import type { CreateStripeCheckoutSessionResponse } from "./spyder_service";
import type { CreateStripeCheckoutSessionRequest } from "./spyder_service";
import type { EndpointConfig } from "./spyder_service";
import type { AuthData } from "./spyder_service";
import type { RedeemAuthDataRequest } from "./spyder_service";
import type { RedemptionCode } from "./spyder_service";
import type { AuthDataRequest } from "./spyder_service";
import type { CopyPathRequest } from "./spyder_service";
import type { RenamePathRequest } from "./spyder_service";
import type { TrashPathRequest } from "./spyder_service";
import type { CreatePathRequest } from "./spyder_service";
import type { DirListing } from "../../common/v1/objects";
import type { ReadDirRequest } from "./spyder_service";
import type { CaffeinateEndpointRequest } from "./spyder_service";
import type { Certificate } from "./spyder_service";
import type { CertificateSigningRequest } from "./spyder_service";
import type { EndpointStatus } from "./spyder_service";
import type { ConnectorExportLocator } from "../../common/v1/objects";
import type { ConnectorExportList } from "./spyder_service";
import type { GetAllConnectorExportsFromMeRequest } from "./spyder_service";
import type { CreateTunnelFromExportRequest } from "./spyder_service";
import type { ConnectorExport } from "./spyder_service";
import type { CreateConnectorExportRequest } from "./spyder_service";
import type { FindTunnelsRequest } from "./spyder_service";
import type { TunnelList } from "../../common/v1/objects";
import type { TunnelLocator } from "../../common/v1/objects";
import type { Tunnel } from "../../common/v1/objects";
import type { CreateTunnelRequest } from "./spyder_service";
import type { PublicKey } from "./spyder_service";
import type { GetPublicKeyRequest } from "./spyder_service";
import type { UpsertPublicKeyRequest } from "./spyder_service";
import type { EndpointList } from "./spyder_service";
import type { EndpointLocator } from "../../common/v1/objects";
import type { Endpoint } from "./spyder_service";
import type { UpsertEndpointRequest } from "./spyder_service";
import type { ClientList } from "./spyder_service";
import type { Client } from "./spyder_service";
import type { CreateClientRequest } from "./spyder_service";
import type { ChatLocator } from "../../common/v1/objects";
import type { ChatList } from "./spyder_service";
import type { GetAllChatRequest } from "./spyder_service";
import type { Chat } from "./spyder_service";
import type { CreateChatRequet } from "./spyder_service";
import type { CreateUserRequest } from "./spyder_service";
import type { User } from "./spyder_service";
import type { UserLocator } from "../../common/v1/objects";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { GrpcResponse } from "./common";
import type { Empty } from "../../../google/protobuf/empty";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * @generated from protobuf service portola.spyder.api.v1.SpyderService
 */
export interface ISpyderServiceClient {
    /**
     * @generated from protobuf rpc: CheckHealth(google.protobuf.Empty) returns (portola.spyder.api.v1.GrpcResponse);
     */
    checkHealth(input: Empty, options?: RpcOptions): UnaryCall<Empty, GrpcResponse>;
    /**
     * Called by portd
     *
     * @generated from protobuf rpc: ImpersonateUser(portola.common.api.v1.UserLocator) returns (portola.spyder.api.v1.User);
     */
    impersonateUser(input: UserLocator, options?: RpcOptions): UnaryCall<UserLocator, User>;
    /**
     * @generated from protobuf rpc: CreateUser(portola.spyder.api.v1.CreateUserRequest) returns (portola.spyder.api.v1.User);
     */
    createUser(input: CreateUserRequest, options?: RpcOptions): UnaryCall<CreateUserRequest, User>;
    /**
     * @generated from protobuf rpc: GetUser(portola.common.api.v1.UserLocator) returns (portola.spyder.api.v1.User);
     */
    getUser(input: UserLocator, options?: RpcOptions): UnaryCall<UserLocator, User>;
    /**
     * @generated from protobuf rpc: CreateChat(portola.spyder.api.v1.CreateChatRequet) returns (portola.spyder.api.v1.Chat);
     */
    createChat(input: CreateChatRequet, options?: RpcOptions): UnaryCall<CreateChatRequet, Chat>;
    /**
     * @generated from protobuf rpc: GetAllChat(portola.spyder.api.v1.GetAllChatRequest) returns (portola.spyder.api.v1.ChatList);
     */
    getAllChat(input: GetAllChatRequest, options?: RpcOptions): UnaryCall<GetAllChatRequest, ChatList>;
    /**
     * @generated from protobuf rpc: DeleteChat(portola.common.api.v1.ChatLocator) returns (google.protobuf.Empty);
     */
    deleteChat(input: ChatLocator, options?: RpcOptions): UnaryCall<ChatLocator, Empty>;
    /**
     * @generated from protobuf rpc: CreateClient(portola.spyder.api.v1.CreateClientRequest) returns (portola.spyder.api.v1.Client);
     */
    createClient(input: CreateClientRequest, options?: RpcOptions): UnaryCall<CreateClientRequest, Client>;
    /**
     * @generated from protobuf rpc: DeleteClient(portola.spyder.api.v1.Client) returns (google.protobuf.Empty);
     */
    deleteClient(input: Client, options?: RpcOptions): UnaryCall<Client, Empty>;
    /**
     * @generated from protobuf rpc: GetAllClients(portola.common.api.v1.UserLocator) returns (portola.spyder.api.v1.ClientList);
     */
    getAllClients(input: UserLocator, options?: RpcOptions): UnaryCall<UserLocator, ClientList>;
    /**
     * @generated from protobuf rpc: UpsertEndpoint(portola.spyder.api.v1.UpsertEndpointRequest) returns (portola.spyder.api.v1.Endpoint);
     */
    upsertEndpoint(input: UpsertEndpointRequest, options?: RpcOptions): UnaryCall<UpsertEndpointRequest, Endpoint>;
    /**
     * @generated from protobuf rpc: GetEndpoint(portola.common.api.v1.EndpointLocator) returns (portola.spyder.api.v1.Endpoint);
     */
    getEndpoint(input: EndpointLocator, options?: RpcOptions): UnaryCall<EndpointLocator, Endpoint>;
    /**
     * @generated from protobuf rpc: GetAllEndpoints(portola.common.api.v1.UserLocator) returns (portola.spyder.api.v1.EndpointList);
     */
    getAllEndpoints(input: UserLocator, options?: RpcOptions): UnaryCall<UserLocator, EndpointList>;
    /**
     * @generated from protobuf rpc: UpsertPublicKey(portola.spyder.api.v1.UpsertPublicKeyRequest) returns (google.protobuf.Empty);
     */
    upsertPublicKey(input: UpsertPublicKeyRequest, options?: RpcOptions): UnaryCall<UpsertPublicKeyRequest, Empty>;
    /**
     * @generated from protobuf rpc: GetPublicKey(portola.spyder.api.v1.GetPublicKeyRequest) returns (portola.spyder.api.v1.PublicKey);
     */
    getPublicKey(input: GetPublicKeyRequest, options?: RpcOptions): UnaryCall<GetPublicKeyRequest, PublicKey>;
    /**
     * Called by portctl/ui - CRUD
     *
     * @generated from protobuf rpc: CreateTunnel(portola.spyder.api.v1.CreateTunnelRequest) returns (portola.common.api.v1.Tunnel);
     */
    createTunnel(input: CreateTunnelRequest, options?: RpcOptions): UnaryCall<CreateTunnelRequest, Tunnel>;
    /**
     * @generated from protobuf rpc: DeleteTunnel(portola.common.api.v1.TunnelLocator) returns (google.protobuf.Empty);
     */
    deleteTunnel(input: TunnelLocator, options?: RpcOptions): UnaryCall<TunnelLocator, Empty>;
    /**
     * @generated from protobuf rpc: GetAllTunnels(portola.common.api.v1.UserLocator) returns (portola.common.api.v1.TunnelList);
     */
    getAllTunnels(input: UserLocator, options?: RpcOptions): UnaryCall<UserLocator, TunnelList>;
    /**
     * @generated from protobuf rpc: FindTunnels(portola.spyder.api.v1.FindTunnelsRequest) returns (portola.common.api.v1.TunnelList);
     */
    findTunnels(input: FindTunnelsRequest, options?: RpcOptions): UnaryCall<FindTunnelsRequest, TunnelList>;
    /**
     * @generated from protobuf rpc: GetTunnel(portola.common.api.v1.TunnelLocator) returns (portola.common.api.v1.Tunnel);
     */
    getTunnel(input: TunnelLocator, options?: RpcOptions): UnaryCall<TunnelLocator, Tunnel>;
    /**
     * @generated from protobuf rpc: CreateConnectorExport(portola.spyder.api.v1.CreateConnectorExportRequest) returns (portola.spyder.api.v1.ConnectorExport);
     */
    createConnectorExport(input: CreateConnectorExportRequest, options?: RpcOptions): UnaryCall<CreateConnectorExportRequest, ConnectorExport>;
    /**
     * @generated from protobuf rpc: CreateTunnelFromExport(portola.spyder.api.v1.CreateTunnelFromExportRequest) returns (portola.common.api.v1.Tunnel);
     */
    createTunnelFromExport(input: CreateTunnelFromExportRequest, options?: RpcOptions): UnaryCall<CreateTunnelFromExportRequest, Tunnel>;
    /**
     * @generated from protobuf rpc: GetAllConnectorExportsFromMe(portola.spyder.api.v1.GetAllConnectorExportsFromMeRequest) returns (portola.spyder.api.v1.ConnectorExportList);
     */
    getAllConnectorExportsFromMe(input: GetAllConnectorExportsFromMeRequest, options?: RpcOptions): UnaryCall<GetAllConnectorExportsFromMeRequest, ConnectorExportList>;
    /**
     * @generated from protobuf rpc: GetAllConnectorExportsToMe(portola.common.api.v1.UserLocator) returns (portola.spyder.api.v1.ConnectorExportList);
     */
    getAllConnectorExportsToMe(input: UserLocator, options?: RpcOptions): UnaryCall<UserLocator, ConnectorExportList>;
    /**
     * @generated from protobuf rpc: DeleteConnectorExport(portola.common.api.v1.ConnectorExportLocator) returns (google.protobuf.Empty);
     */
    deleteConnectorExport(input: ConnectorExportLocator, options?: RpcOptions): UnaryCall<ConnectorExportLocator, Empty>;
    /**
     * @generated from protobuf rpc: GetEndpointStatus(portola.common.api.v1.EndpointLocator) returns (portola.spyder.api.v1.EndpointStatus);
     */
    getEndpointStatus(input: EndpointLocator, options?: RpcOptions): UnaryCall<EndpointLocator, EndpointStatus>;
    /**
     * CA
     *
     * @generated from protobuf rpc: GenerateSingedCert(portola.spyder.api.v1.CertificateSigningRequest) returns (portola.spyder.api.v1.Certificate);
     */
    generateSingedCert(input: CertificateSigningRequest, options?: RpcOptions): UnaryCall<CertificateSigningRequest, Certificate>;
    /**
     * Upgrade
     *
     * @generated from protobuf rpc: CaffeinateEndpoint(portola.spyder.api.v1.CaffeinateEndpointRequest) returns (google.protobuf.Empty);
     */
    caffeinateEndpoint(input: CaffeinateEndpointRequest, options?: RpcOptions): UnaryCall<CaffeinateEndpointRequest, Empty>;
    /**
     * @generated from protobuf rpc: FsReadDir(portola.spyder.api.v1.ReadDirRequest) returns (portola.common.api.v1.DirListing);
     */
    fsReadDir(input: ReadDirRequest, options?: RpcOptions): UnaryCall<ReadDirRequest, DirListing>;
    /**
     * @generated from protobuf rpc: FsCreatePath(portola.spyder.api.v1.CreatePathRequest) returns (google.protobuf.Empty);
     */
    fsCreatePath(input: CreatePathRequest, options?: RpcOptions): UnaryCall<CreatePathRequest, Empty>;
    /**
     * @generated from protobuf rpc: FsTrashPath(portola.spyder.api.v1.TrashPathRequest) returns (google.protobuf.Empty);
     */
    fsTrashPath(input: TrashPathRequest, options?: RpcOptions): UnaryCall<TrashPathRequest, Empty>;
    /**
     * @generated from protobuf rpc: FsRenamePath(portola.spyder.api.v1.RenamePathRequest) returns (google.protobuf.Empty);
     */
    fsRenamePath(input: RenamePathRequest, options?: RpcOptions): UnaryCall<RenamePathRequest, Empty>;
    /**
     * @generated from protobuf rpc: FsCopyPath(portola.spyder.api.v1.CopyPathRequest) returns (google.protobuf.Empty);
     */
    fsCopyPath(input: CopyPathRequest, options?: RpcOptions): UnaryCall<CopyPathRequest, Empty>;
    /**
     * @generated from protobuf rpc: PutAuthData(portola.spyder.api.v1.AuthDataRequest) returns (portola.spyder.api.v1.RedemptionCode);
     */
    putAuthData(input: AuthDataRequest, options?: RpcOptions): UnaryCall<AuthDataRequest, RedemptionCode>;
    /**
     * @generated from protobuf rpc: RedeemAuthData(portola.spyder.api.v1.RedeemAuthDataRequest) returns (portola.spyder.api.v1.AuthData);
     */
    redeemAuthData(input: RedeemAuthDataRequest, options?: RpcOptions): UnaryCall<RedeemAuthDataRequest, AuthData>;
    /**
     * Run time config for Endpoint Service
     *
     * @generated from protobuf rpc: GetEndpointConfig(portola.common.api.v1.EndpointLocator) returns (portola.spyder.api.v1.EndpointConfig);
     */
    getEndpointConfig(input: EndpointLocator, options?: RpcOptions): UnaryCall<EndpointLocator, EndpointConfig>;
    /**
     * Stripe
     *
     * @generated from protobuf rpc: CreateStripeCheckoutSession(portola.spyder.api.v1.CreateStripeCheckoutSessionRequest) returns (portola.spyder.api.v1.CreateStripeCheckoutSessionResponse);
     */
    createStripeCheckoutSession(input: CreateStripeCheckoutSessionRequest, options?: RpcOptions): UnaryCall<CreateStripeCheckoutSessionRequest, CreateStripeCheckoutSessionResponse>;
    /**
     * rpc StripeHandleWebhook (StripeWebhookRequest) returns (StripeWebhookResponse);
     *
     * @generated from protobuf rpc: CreateStripePortalSession(portola.spyder.api.v1.CreateStripePortalSessionRequest) returns (portola.spyder.api.v1.CreateStripePortalSessionResponse);
     */
    createStripePortalSession(input: CreateStripePortalSessionRequest, options?: RpcOptions): UnaryCall<CreateStripePortalSessionRequest, CreateStripePortalSessionResponse>;
    /**
     * Auth
     *
     * @generated from protobuf rpc: AuthenticateClient(portola.spyder.api.v1.Client) returns (portola.spyder.api.v1.Token);
     */
    authenticateClient(input: Client, options?: RpcOptions): UnaryCall<Client, Token>;
}
/**
 * @generated from protobuf service portola.spyder.api.v1.SpyderService
 */
export class SpyderServiceClient implements ISpyderServiceClient, ServiceInfo {
    typeName = SpyderService.typeName;
    methods = SpyderService.methods;
    options = SpyderService.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: CheckHealth(google.protobuf.Empty) returns (portola.spyder.api.v1.GrpcResponse);
     */
    checkHealth(input: Empty, options?: RpcOptions): UnaryCall<Empty, GrpcResponse> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<Empty, GrpcResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * Called by portd
     *
     * @generated from protobuf rpc: ImpersonateUser(portola.common.api.v1.UserLocator) returns (portola.spyder.api.v1.User);
     */
    impersonateUser(input: UserLocator, options?: RpcOptions): UnaryCall<UserLocator, User> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<UserLocator, User>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: CreateUser(portola.spyder.api.v1.CreateUserRequest) returns (portola.spyder.api.v1.User);
     */
    createUser(input: CreateUserRequest, options?: RpcOptions): UnaryCall<CreateUserRequest, User> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return stackIntercept<CreateUserRequest, User>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetUser(portola.common.api.v1.UserLocator) returns (portola.spyder.api.v1.User);
     */
    getUser(input: UserLocator, options?: RpcOptions): UnaryCall<UserLocator, User> {
        const method = this.methods[3], opt = this._transport.mergeOptions(options);
        return stackIntercept<UserLocator, User>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: CreateChat(portola.spyder.api.v1.CreateChatRequet) returns (portola.spyder.api.v1.Chat);
     */
    createChat(input: CreateChatRequet, options?: RpcOptions): UnaryCall<CreateChatRequet, Chat> {
        const method = this.methods[4], opt = this._transport.mergeOptions(options);
        return stackIntercept<CreateChatRequet, Chat>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetAllChat(portola.spyder.api.v1.GetAllChatRequest) returns (portola.spyder.api.v1.ChatList);
     */
    getAllChat(input: GetAllChatRequest, options?: RpcOptions): UnaryCall<GetAllChatRequest, ChatList> {
        const method = this.methods[5], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetAllChatRequest, ChatList>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: DeleteChat(portola.common.api.v1.ChatLocator) returns (google.protobuf.Empty);
     */
    deleteChat(input: ChatLocator, options?: RpcOptions): UnaryCall<ChatLocator, Empty> {
        const method = this.methods[6], opt = this._transport.mergeOptions(options);
        return stackIntercept<ChatLocator, Empty>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: CreateClient(portola.spyder.api.v1.CreateClientRequest) returns (portola.spyder.api.v1.Client);
     */
    createClient(input: CreateClientRequest, options?: RpcOptions): UnaryCall<CreateClientRequest, Client> {
        const method = this.methods[7], opt = this._transport.mergeOptions(options);
        return stackIntercept<CreateClientRequest, Client>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: DeleteClient(portola.spyder.api.v1.Client) returns (google.protobuf.Empty);
     */
    deleteClient(input: Client, options?: RpcOptions): UnaryCall<Client, Empty> {
        const method = this.methods[8], opt = this._transport.mergeOptions(options);
        return stackIntercept<Client, Empty>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetAllClients(portola.common.api.v1.UserLocator) returns (portola.spyder.api.v1.ClientList);
     */
    getAllClients(input: UserLocator, options?: RpcOptions): UnaryCall<UserLocator, ClientList> {
        const method = this.methods[9], opt = this._transport.mergeOptions(options);
        return stackIntercept<UserLocator, ClientList>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: UpsertEndpoint(portola.spyder.api.v1.UpsertEndpointRequest) returns (portola.spyder.api.v1.Endpoint);
     */
    upsertEndpoint(input: UpsertEndpointRequest, options?: RpcOptions): UnaryCall<UpsertEndpointRequest, Endpoint> {
        const method = this.methods[10], opt = this._transport.mergeOptions(options);
        return stackIntercept<UpsertEndpointRequest, Endpoint>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetEndpoint(portola.common.api.v1.EndpointLocator) returns (portola.spyder.api.v1.Endpoint);
     */
    getEndpoint(input: EndpointLocator, options?: RpcOptions): UnaryCall<EndpointLocator, Endpoint> {
        const method = this.methods[11], opt = this._transport.mergeOptions(options);
        return stackIntercept<EndpointLocator, Endpoint>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetAllEndpoints(portola.common.api.v1.UserLocator) returns (portola.spyder.api.v1.EndpointList);
     */
    getAllEndpoints(input: UserLocator, options?: RpcOptions): UnaryCall<UserLocator, EndpointList> {
        const method = this.methods[12], opt = this._transport.mergeOptions(options);
        return stackIntercept<UserLocator, EndpointList>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: UpsertPublicKey(portola.spyder.api.v1.UpsertPublicKeyRequest) returns (google.protobuf.Empty);
     */
    upsertPublicKey(input: UpsertPublicKeyRequest, options?: RpcOptions): UnaryCall<UpsertPublicKeyRequest, Empty> {
        const method = this.methods[13], opt = this._transport.mergeOptions(options);
        return stackIntercept<UpsertPublicKeyRequest, Empty>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetPublicKey(portola.spyder.api.v1.GetPublicKeyRequest) returns (portola.spyder.api.v1.PublicKey);
     */
    getPublicKey(input: GetPublicKeyRequest, options?: RpcOptions): UnaryCall<GetPublicKeyRequest, PublicKey> {
        const method = this.methods[14], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetPublicKeyRequest, PublicKey>("unary", this._transport, method, opt, input);
    }
    /**
     * Called by portctl/ui - CRUD
     *
     * @generated from protobuf rpc: CreateTunnel(portola.spyder.api.v1.CreateTunnelRequest) returns (portola.common.api.v1.Tunnel);
     */
    createTunnel(input: CreateTunnelRequest, options?: RpcOptions): UnaryCall<CreateTunnelRequest, Tunnel> {
        const method = this.methods[15], opt = this._transport.mergeOptions(options);
        return stackIntercept<CreateTunnelRequest, Tunnel>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: DeleteTunnel(portola.common.api.v1.TunnelLocator) returns (google.protobuf.Empty);
     */
    deleteTunnel(input: TunnelLocator, options?: RpcOptions): UnaryCall<TunnelLocator, Empty> {
        const method = this.methods[16], opt = this._transport.mergeOptions(options);
        return stackIntercept<TunnelLocator, Empty>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetAllTunnels(portola.common.api.v1.UserLocator) returns (portola.common.api.v1.TunnelList);
     */
    getAllTunnels(input: UserLocator, options?: RpcOptions): UnaryCall<UserLocator, TunnelList> {
        const method = this.methods[17], opt = this._transport.mergeOptions(options);
        return stackIntercept<UserLocator, TunnelList>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: FindTunnels(portola.spyder.api.v1.FindTunnelsRequest) returns (portola.common.api.v1.TunnelList);
     */
    findTunnels(input: FindTunnelsRequest, options?: RpcOptions): UnaryCall<FindTunnelsRequest, TunnelList> {
        const method = this.methods[18], opt = this._transport.mergeOptions(options);
        return stackIntercept<FindTunnelsRequest, TunnelList>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetTunnel(portola.common.api.v1.TunnelLocator) returns (portola.common.api.v1.Tunnel);
     */
    getTunnel(input: TunnelLocator, options?: RpcOptions): UnaryCall<TunnelLocator, Tunnel> {
        const method = this.methods[19], opt = this._transport.mergeOptions(options);
        return stackIntercept<TunnelLocator, Tunnel>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: CreateConnectorExport(portola.spyder.api.v1.CreateConnectorExportRequest) returns (portola.spyder.api.v1.ConnectorExport);
     */
    createConnectorExport(input: CreateConnectorExportRequest, options?: RpcOptions): UnaryCall<CreateConnectorExportRequest, ConnectorExport> {
        const method = this.methods[20], opt = this._transport.mergeOptions(options);
        return stackIntercept<CreateConnectorExportRequest, ConnectorExport>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: CreateTunnelFromExport(portola.spyder.api.v1.CreateTunnelFromExportRequest) returns (portola.common.api.v1.Tunnel);
     */
    createTunnelFromExport(input: CreateTunnelFromExportRequest, options?: RpcOptions): UnaryCall<CreateTunnelFromExportRequest, Tunnel> {
        const method = this.methods[21], opt = this._transport.mergeOptions(options);
        return stackIntercept<CreateTunnelFromExportRequest, Tunnel>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetAllConnectorExportsFromMe(portola.spyder.api.v1.GetAllConnectorExportsFromMeRequest) returns (portola.spyder.api.v1.ConnectorExportList);
     */
    getAllConnectorExportsFromMe(input: GetAllConnectorExportsFromMeRequest, options?: RpcOptions): UnaryCall<GetAllConnectorExportsFromMeRequest, ConnectorExportList> {
        const method = this.methods[22], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetAllConnectorExportsFromMeRequest, ConnectorExportList>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetAllConnectorExportsToMe(portola.common.api.v1.UserLocator) returns (portola.spyder.api.v1.ConnectorExportList);
     */
    getAllConnectorExportsToMe(input: UserLocator, options?: RpcOptions): UnaryCall<UserLocator, ConnectorExportList> {
        const method = this.methods[23], opt = this._transport.mergeOptions(options);
        return stackIntercept<UserLocator, ConnectorExportList>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: DeleteConnectorExport(portola.common.api.v1.ConnectorExportLocator) returns (google.protobuf.Empty);
     */
    deleteConnectorExport(input: ConnectorExportLocator, options?: RpcOptions): UnaryCall<ConnectorExportLocator, Empty> {
        const method = this.methods[24], opt = this._transport.mergeOptions(options);
        return stackIntercept<ConnectorExportLocator, Empty>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetEndpointStatus(portola.common.api.v1.EndpointLocator) returns (portola.spyder.api.v1.EndpointStatus);
     */
    getEndpointStatus(input: EndpointLocator, options?: RpcOptions): UnaryCall<EndpointLocator, EndpointStatus> {
        const method = this.methods[25], opt = this._transport.mergeOptions(options);
        return stackIntercept<EndpointLocator, EndpointStatus>("unary", this._transport, method, opt, input);
    }
    /**
     * CA
     *
     * @generated from protobuf rpc: GenerateSingedCert(portola.spyder.api.v1.CertificateSigningRequest) returns (portola.spyder.api.v1.Certificate);
     */
    generateSingedCert(input: CertificateSigningRequest, options?: RpcOptions): UnaryCall<CertificateSigningRequest, Certificate> {
        const method = this.methods[26], opt = this._transport.mergeOptions(options);
        return stackIntercept<CertificateSigningRequest, Certificate>("unary", this._transport, method, opt, input);
    }
    /**
     * Upgrade
     *
     * @generated from protobuf rpc: CaffeinateEndpoint(portola.spyder.api.v1.CaffeinateEndpointRequest) returns (google.protobuf.Empty);
     */
    caffeinateEndpoint(input: CaffeinateEndpointRequest, options?: RpcOptions): UnaryCall<CaffeinateEndpointRequest, Empty> {
        const method = this.methods[27], opt = this._transport.mergeOptions(options);
        return stackIntercept<CaffeinateEndpointRequest, Empty>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: FsReadDir(portola.spyder.api.v1.ReadDirRequest) returns (portola.common.api.v1.DirListing);
     */
    fsReadDir(input: ReadDirRequest, options?: RpcOptions): UnaryCall<ReadDirRequest, DirListing> {
        const method = this.methods[28], opt = this._transport.mergeOptions(options);
        return stackIntercept<ReadDirRequest, DirListing>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: FsCreatePath(portola.spyder.api.v1.CreatePathRequest) returns (google.protobuf.Empty);
     */
    fsCreatePath(input: CreatePathRequest, options?: RpcOptions): UnaryCall<CreatePathRequest, Empty> {
        const method = this.methods[29], opt = this._transport.mergeOptions(options);
        return stackIntercept<CreatePathRequest, Empty>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: FsTrashPath(portola.spyder.api.v1.TrashPathRequest) returns (google.protobuf.Empty);
     */
    fsTrashPath(input: TrashPathRequest, options?: RpcOptions): UnaryCall<TrashPathRequest, Empty> {
        const method = this.methods[30], opt = this._transport.mergeOptions(options);
        return stackIntercept<TrashPathRequest, Empty>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: FsRenamePath(portola.spyder.api.v1.RenamePathRequest) returns (google.protobuf.Empty);
     */
    fsRenamePath(input: RenamePathRequest, options?: RpcOptions): UnaryCall<RenamePathRequest, Empty> {
        const method = this.methods[31], opt = this._transport.mergeOptions(options);
        return stackIntercept<RenamePathRequest, Empty>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: FsCopyPath(portola.spyder.api.v1.CopyPathRequest) returns (google.protobuf.Empty);
     */
    fsCopyPath(input: CopyPathRequest, options?: RpcOptions): UnaryCall<CopyPathRequest, Empty> {
        const method = this.methods[32], opt = this._transport.mergeOptions(options);
        return stackIntercept<CopyPathRequest, Empty>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: PutAuthData(portola.spyder.api.v1.AuthDataRequest) returns (portola.spyder.api.v1.RedemptionCode);
     */
    putAuthData(input: AuthDataRequest, options?: RpcOptions): UnaryCall<AuthDataRequest, RedemptionCode> {
        const method = this.methods[33], opt = this._transport.mergeOptions(options);
        return stackIntercept<AuthDataRequest, RedemptionCode>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: RedeemAuthData(portola.spyder.api.v1.RedeemAuthDataRequest) returns (portola.spyder.api.v1.AuthData);
     */
    redeemAuthData(input: RedeemAuthDataRequest, options?: RpcOptions): UnaryCall<RedeemAuthDataRequest, AuthData> {
        const method = this.methods[34], opt = this._transport.mergeOptions(options);
        return stackIntercept<RedeemAuthDataRequest, AuthData>("unary", this._transport, method, opt, input);
    }
    /**
     * Run time config for Endpoint Service
     *
     * @generated from protobuf rpc: GetEndpointConfig(portola.common.api.v1.EndpointLocator) returns (portola.spyder.api.v1.EndpointConfig);
     */
    getEndpointConfig(input: EndpointLocator, options?: RpcOptions): UnaryCall<EndpointLocator, EndpointConfig> {
        const method = this.methods[35], opt = this._transport.mergeOptions(options);
        return stackIntercept<EndpointLocator, EndpointConfig>("unary", this._transport, method, opt, input);
    }
    /**
     * Stripe
     *
     * @generated from protobuf rpc: CreateStripeCheckoutSession(portola.spyder.api.v1.CreateStripeCheckoutSessionRequest) returns (portola.spyder.api.v1.CreateStripeCheckoutSessionResponse);
     */
    createStripeCheckoutSession(input: CreateStripeCheckoutSessionRequest, options?: RpcOptions): UnaryCall<CreateStripeCheckoutSessionRequest, CreateStripeCheckoutSessionResponse> {
        const method = this.methods[36], opt = this._transport.mergeOptions(options);
        return stackIntercept<CreateStripeCheckoutSessionRequest, CreateStripeCheckoutSessionResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * rpc StripeHandleWebhook (StripeWebhookRequest) returns (StripeWebhookResponse);
     *
     * @generated from protobuf rpc: CreateStripePortalSession(portola.spyder.api.v1.CreateStripePortalSessionRequest) returns (portola.spyder.api.v1.CreateStripePortalSessionResponse);
     */
    createStripePortalSession(input: CreateStripePortalSessionRequest, options?: RpcOptions): UnaryCall<CreateStripePortalSessionRequest, CreateStripePortalSessionResponse> {
        const method = this.methods[37], opt = this._transport.mergeOptions(options);
        return stackIntercept<CreateStripePortalSessionRequest, CreateStripePortalSessionResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * Auth
     *
     * @generated from protobuf rpc: AuthenticateClient(portola.spyder.api.v1.Client) returns (portola.spyder.api.v1.Token);
     */
    authenticateClient(input: Client, options?: RpcOptions): UnaryCall<Client, Token> {
        const method = this.methods[38], opt = this._transport.mergeOptions(options);
        return stackIntercept<Client, Token>("unary", this._transport, method, opt, input);
    }
}
