// @generated by protobuf-ts 2.9.4
// @generated from protobuf file "dragon/turnstile/v1/turnstile_service.proto" (package "dragon.turnstile.v1", syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { TurnstileService } from "./turnstile_service";
import type { UnloadToolsForMcpServerRequest } from "./turnstile_service";
import type { LoadToolsForMcpServerRequest } from "./turnstile_service";
import type { LogoutMcpServerRequest } from "./turnstile_service";
import type { McpServerLoginUrl } from "./turnstile_service";
import type { LoginMcpServerRequest } from "./turnstile_service";
import type { McpServerLoginStatus } from "./turnstile_service";
import type { GetLoginStatusForMcpServerRequest } from "./turnstile_service";
import type { Empty } from "../../../google/protobuf/empty";
import type { RemoveMcpServerRequest } from "./turnstile_service";
import type { McpServer } from "./turnstile_service";
import type { AddMcpServerRequest } from "./turnstile_service";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { McpServerList } from "./turnstile_service";
import type { ListMcpServersRequest } from "./turnstile_service";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * @generated from protobuf service dragon.turnstile.v1.TurnstileService
 */
export interface ITurnstileServiceClient {
    /**
     * @generated from protobuf rpc: ListMcpServers(dragon.turnstile.v1.ListMcpServersRequest) returns (dragon.turnstile.v1.McpServerList);
     */
    listMcpServers(input: ListMcpServersRequest, options?: RpcOptions): UnaryCall<ListMcpServersRequest, McpServerList>;
    /**
     * @generated from protobuf rpc: AddMcpServer(dragon.turnstile.v1.AddMcpServerRequest) returns (dragon.turnstile.v1.McpServer);
     */
    addMcpServer(input: AddMcpServerRequest, options?: RpcOptions): UnaryCall<AddMcpServerRequest, McpServer>;
    /**
     * @generated from protobuf rpc: RemoveMcpServer(dragon.turnstile.v1.RemoveMcpServerRequest) returns (google.protobuf.Empty);
     */
    removeMcpServer(input: RemoveMcpServerRequest, options?: RpcOptions): UnaryCall<RemoveMcpServerRequest, Empty>;
    /**
     * @generated from protobuf rpc: GetLoginStatusForMcpServer(dragon.turnstile.v1.GetLoginStatusForMcpServerRequest) returns (dragon.turnstile.v1.McpServerLoginStatus);
     */
    getLoginStatusForMcpServer(input: GetLoginStatusForMcpServerRequest, options?: RpcOptions): UnaryCall<GetLoginStatusForMcpServerRequest, McpServerLoginStatus>;
    /**
     * @generated from protobuf rpc: LoginMcpServer(dragon.turnstile.v1.LoginMcpServerRequest) returns (dragon.turnstile.v1.McpServerLoginUrl);
     */
    loginMcpServer(input: LoginMcpServerRequest, options?: RpcOptions): UnaryCall<LoginMcpServerRequest, McpServerLoginUrl>;
    /**
     * @generated from protobuf rpc: LogoutMcpServer(dragon.turnstile.v1.LogoutMcpServerRequest) returns (google.protobuf.Empty);
     */
    logoutMcpServer(input: LogoutMcpServerRequest, options?: RpcOptions): UnaryCall<LogoutMcpServerRequest, Empty>;
    /**
     * @generated from protobuf rpc: LoadToolsForMcpServer(dragon.turnstile.v1.LoadToolsForMcpServerRequest) returns (google.protobuf.Empty);
     */
    loadToolsForMcpServer(input: LoadToolsForMcpServerRequest, options?: RpcOptions): UnaryCall<LoadToolsForMcpServerRequest, Empty>;
    /**
     * @generated from protobuf rpc: UnloadToolsForMcpServer(dragon.turnstile.v1.UnloadToolsForMcpServerRequest) returns (google.protobuf.Empty);
     */
    unloadToolsForMcpServer(input: UnloadToolsForMcpServerRequest, options?: RpcOptions): UnaryCall<UnloadToolsForMcpServerRequest, Empty>;
}
/**
 * @generated from protobuf service dragon.turnstile.v1.TurnstileService
 */
export class TurnstileServiceClient implements ITurnstileServiceClient, ServiceInfo {
    typeName = TurnstileService.typeName;
    methods = TurnstileService.methods;
    options = TurnstileService.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: ListMcpServers(dragon.turnstile.v1.ListMcpServersRequest) returns (dragon.turnstile.v1.McpServerList);
     */
    listMcpServers(input: ListMcpServersRequest, options?: RpcOptions): UnaryCall<ListMcpServersRequest, McpServerList> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<ListMcpServersRequest, McpServerList>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: AddMcpServer(dragon.turnstile.v1.AddMcpServerRequest) returns (dragon.turnstile.v1.McpServer);
     */
    addMcpServer(input: AddMcpServerRequest, options?: RpcOptions): UnaryCall<AddMcpServerRequest, McpServer> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<AddMcpServerRequest, McpServer>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: RemoveMcpServer(dragon.turnstile.v1.RemoveMcpServerRequest) returns (google.protobuf.Empty);
     */
    removeMcpServer(input: RemoveMcpServerRequest, options?: RpcOptions): UnaryCall<RemoveMcpServerRequest, Empty> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return stackIntercept<RemoveMcpServerRequest, Empty>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetLoginStatusForMcpServer(dragon.turnstile.v1.GetLoginStatusForMcpServerRequest) returns (dragon.turnstile.v1.McpServerLoginStatus);
     */
    getLoginStatusForMcpServer(input: GetLoginStatusForMcpServerRequest, options?: RpcOptions): UnaryCall<GetLoginStatusForMcpServerRequest, McpServerLoginStatus> {
        const method = this.methods[3], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetLoginStatusForMcpServerRequest, McpServerLoginStatus>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: LoginMcpServer(dragon.turnstile.v1.LoginMcpServerRequest) returns (dragon.turnstile.v1.McpServerLoginUrl);
     */
    loginMcpServer(input: LoginMcpServerRequest, options?: RpcOptions): UnaryCall<LoginMcpServerRequest, McpServerLoginUrl> {
        const method = this.methods[4], opt = this._transport.mergeOptions(options);
        return stackIntercept<LoginMcpServerRequest, McpServerLoginUrl>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: LogoutMcpServer(dragon.turnstile.v1.LogoutMcpServerRequest) returns (google.protobuf.Empty);
     */
    logoutMcpServer(input: LogoutMcpServerRequest, options?: RpcOptions): UnaryCall<LogoutMcpServerRequest, Empty> {
        const method = this.methods[5], opt = this._transport.mergeOptions(options);
        return stackIntercept<LogoutMcpServerRequest, Empty>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: LoadToolsForMcpServer(dragon.turnstile.v1.LoadToolsForMcpServerRequest) returns (google.protobuf.Empty);
     */
    loadToolsForMcpServer(input: LoadToolsForMcpServerRequest, options?: RpcOptions): UnaryCall<LoadToolsForMcpServerRequest, Empty> {
        const method = this.methods[6], opt = this._transport.mergeOptions(options);
        return stackIntercept<LoadToolsForMcpServerRequest, Empty>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: UnloadToolsForMcpServer(dragon.turnstile.v1.UnloadToolsForMcpServerRequest) returns (google.protobuf.Empty);
     */
    unloadToolsForMcpServer(input: UnloadToolsForMcpServerRequest, options?: RpcOptions): UnaryCall<UnloadToolsForMcpServerRequest, Empty> {
        const method = this.methods[7], opt = this._transport.mergeOptions(options);
        return stackIntercept<UnloadToolsForMcpServerRequest, Empty>("unary", this._transport, method, opt, input);
    }
}
