// @generated by protobuf-ts 2.9.4
// @generated from protobuf file "dragon/turnstile/v1/turnstile_service.proto" (package "dragon.turnstile.v1", syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { TurnstileService } from "./turnstile_service";
import type { LogoutMcpServerRequest } from "./turnstile_service";
import type { McpServerLoginUrl } from "./turnstile_service";
import type { LoginMcpServerRequest } from "./turnstile_service";
import type { McpServerLoginStatus } from "./turnstile_service";
import type { GetLoginStatusForMcpServerRequest } from "./turnstile_service";
import type { Empty } from "../../../google/protobuf/empty";
import type { DeleteMcpServerRequest } from "./turnstile_service";
import type { McpServer } from "./turnstile_service";
import type { CreateMcpServerRequest } from "./turnstile_service";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { McpServerList } from "./turnstile_service";
import type { ListMcpServersRequest } from "./turnstile_service";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * @generated from protobuf service dragon.turnstile.v1.TurnstileService
 */
export interface ITurnstileServiceClient {
    /**
     * @generated from protobuf rpc: ListMcpServers(dragon.turnstile.v1.ListMcpServersRequest) returns (dragon.turnstile.v1.McpServerList);
     */
    listMcpServers(input: ListMcpServersRequest, options?: RpcOptions): UnaryCall<ListMcpServersRequest, McpServerList>;
    /**
     * @generated from protobuf rpc: CreateMcpServer(dragon.turnstile.v1.CreateMcpServerRequest) returns (dragon.turnstile.v1.McpServer);
     */
    createMcpServer(input: CreateMcpServerRequest, options?: RpcOptions): UnaryCall<CreateMcpServerRequest, McpServer>;
    /**
     * @generated from protobuf rpc: DeleteMcpServer(dragon.turnstile.v1.DeleteMcpServerRequest) returns (google.protobuf.Empty);
     */
    deleteMcpServer(input: DeleteMcpServerRequest, options?: RpcOptions): UnaryCall<DeleteMcpServerRequest, Empty>;
    /**
     * @generated from protobuf rpc: GetLoginStatusForMcpServer(dragon.turnstile.v1.GetLoginStatusForMcpServerRequest) returns (dragon.turnstile.v1.McpServerLoginStatus);
     */
    getLoginStatusForMcpServer(input: GetLoginStatusForMcpServerRequest, options?: RpcOptions): UnaryCall<GetLoginStatusForMcpServerRequest, McpServerLoginStatus>;
    /**
     * @generated from protobuf rpc: LoginMcpServer(dragon.turnstile.v1.LoginMcpServerRequest) returns (dragon.turnstile.v1.McpServerLoginUrl);
     */
    loginMcpServer(input: LoginMcpServerRequest, options?: RpcOptions): UnaryCall<LoginMcpServerRequest, McpServerLoginUrl>;
    /**
     * @generated from protobuf rpc: LogoutMcpServer(dragon.turnstile.v1.LogoutMcpServerRequest) returns (google.protobuf.Empty);
     */
    logoutMcpServer(input: LogoutMcpServerRequest, options?: RpcOptions): UnaryCall<LogoutMcpServerRequest, Empty>;
}
/**
 * @generated from protobuf service dragon.turnstile.v1.TurnstileService
 */
export class TurnstileServiceClient implements ITurnstileServiceClient, ServiceInfo {
    typeName = TurnstileService.typeName;
    methods = TurnstileService.methods;
    options = TurnstileService.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: ListMcpServers(dragon.turnstile.v1.ListMcpServersRequest) returns (dragon.turnstile.v1.McpServerList);
     */
    listMcpServers(input: ListMcpServersRequest, options?: RpcOptions): UnaryCall<ListMcpServersRequest, McpServerList> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<ListMcpServersRequest, McpServerList>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: CreateMcpServer(dragon.turnstile.v1.CreateMcpServerRequest) returns (dragon.turnstile.v1.McpServer);
     */
    createMcpServer(input: CreateMcpServerRequest, options?: RpcOptions): UnaryCall<CreateMcpServerRequest, McpServer> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<CreateMcpServerRequest, McpServer>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: DeleteMcpServer(dragon.turnstile.v1.DeleteMcpServerRequest) returns (google.protobuf.Empty);
     */
    deleteMcpServer(input: DeleteMcpServerRequest, options?: RpcOptions): UnaryCall<DeleteMcpServerRequest, Empty> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return stackIntercept<DeleteMcpServerRequest, Empty>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetLoginStatusForMcpServer(dragon.turnstile.v1.GetLoginStatusForMcpServerRequest) returns (dragon.turnstile.v1.McpServerLoginStatus);
     */
    getLoginStatusForMcpServer(input: GetLoginStatusForMcpServerRequest, options?: RpcOptions): UnaryCall<GetLoginStatusForMcpServerRequest, McpServerLoginStatus> {
        const method = this.methods[3], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetLoginStatusForMcpServerRequest, McpServerLoginStatus>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: LoginMcpServer(dragon.turnstile.v1.LoginMcpServerRequest) returns (dragon.turnstile.v1.McpServerLoginUrl);
     */
    loginMcpServer(input: LoginMcpServerRequest, options?: RpcOptions): UnaryCall<LoginMcpServerRequest, McpServerLoginUrl> {
        const method = this.methods[4], opt = this._transport.mergeOptions(options);
        return stackIntercept<LoginMcpServerRequest, McpServerLoginUrl>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: LogoutMcpServer(dragon.turnstile.v1.LogoutMcpServerRequest) returns (google.protobuf.Empty);
     */
    logoutMcpServer(input: LogoutMcpServerRequest, options?: RpcOptions): UnaryCall<LogoutMcpServerRequest, Empty> {
        const method = this.methods[5], opt = this._transport.mergeOptions(options);
        return stackIntercept<LogoutMcpServerRequest, Empty>("unary", this._transport, method, opt, input);
    }
}
